//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub address: String,
    #[sea_orm(unique)]
    pub private_key: String,
    pub proxy: Option<String>,
    pub current_ambient_swaps_count: i32,
    pub target_ambient_swaps_count: i32,
    pub current_apriori_deposit_count: i32,
    pub target_apriori_deposit_count: i32,
    pub current_bean_swaps_count: i32,
    pub target_bean_swaps_count: i32,
    pub current_hashflow_swaps_count: i32,
    pub target_hashflow_swaps_count: i32,
    pub current_kinza_deposit_count: i32,
    pub target_kinza_deposit_count: i32,
    pub current_shmonad_deposit_count: i32,
    pub target_shmonad_deposit_count: i32,
    pub current_nad_domains_count: i32,
    pub target_nad_domains_count: i32,
    pub bridge_goal: bool,
    pub goal_reached: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
